"""Generate polylinker-bench: a public truth set for plasmid operations.

The point of this file is that **Polylinker's own engine is never consulted**.
Every expected value comes from an independent tool:

    identity   seguid 0.2.1        (Bjorn Johansson) -- the checksum reference
    digest     Biopython           Bio.Restriction
    pcr        pydna               Dseqrecord + amplify
    assembly   pydna               Assembly / homologous recombination

A benchmark generated by the tool it grades is worth nothing. If Polylinker and
the oracle disagree, the bench says the oracle is right and Polylinker fails,
which is the only arrangement under which a published pass rate means anything.

All sequences are synthetic, so the whole set is redistributable under CC0.
Real plasmid files are not: Addgene's terms are noncommercial-only with an
explicit anti-scraping clause, and lab files belong to their labs.

Usage:
    python bench/generate.py > bench/polylinker-bench.json
"""

import json
import random
import sys

from Bio.Seq import Seq
from Bio import Restriction
from seguid import cdseguid, ldseguid, lsseguid

BENCH_VERSION = "0.1.0"

# Enzymes shared by Polylinker's built-in set and Biopython, so a disagreement
# is about the algorithm rather than about which enzymes exist.
ENZYMES = [
    "EcoRI", "BamHI", "HindIII", "NotI", "XhoI", "SalI", "PstI", "SmaI",
    "XmaI", "KpnI", "SacI", "NcoI", "NdeI", "SpeI", "XbaI", "EcoRV",
    "DraI", "PvuII", "AscI", "PacI",
]

rng = random.Random(20260726)


def rc(s):
    return s.translate(str.maketrans("ACGT", "TGCA"))[::-1]


def rand_seq(n):
    return "".join(rng.choice("ACGT") for _ in range(n))


def case(cid, operation, tier, description, inp, params, expect, oracle):
    return {
        "id": cid,
        "operation": operation,
        "hazard_tier": tier,
        "description": description,
        "input": inp,
        "params": params,
        "expect": expect,
        "oracle": oracle,
    }


# ---------------------------------------------------------------------------
# identity: is this the same molecule?
# ---------------------------------------------------------------------------

def identity_cases():
    """Rotation and strand invariance -- the freedoms a circular duplex has.

    A tool that fails these cannot answer 'did my cloning work' at all, because
    it will call a correct product wrong whenever it comes back rotated.
    """
    out = []
    seqs = [
        ("random-1kb", rand_seq(1000)),
        ("random-137", rand_seq(137)),
        ("palindromic", "GAATTC" * 12),
        ("homopolymer-run", "A" * 40 + rand_seq(60)),
        ("periodic", "ATCG" * 40),
        ("near-periodic", "ATCG" * 39 + "ATCA"),
        ("at-rich", "".join(rng.choice("AT") for _ in range(200))),
    ]
    for name, s in seqs:
        expected = cdseguid(s, rc(s))
        out.append(case(
            f"identity/circular-{name}", "identity", 1,
            "cdseguid of a circular duplex",
            {"topology": "circular", "sequence": s},
            {},
            {"cdseguid": expected},
            {"tool": "seguid", "version": "0.2.1"},
        ))
        # The same molecule, cut open somewhere else. Must be identical.
        for k in (1, len(s) // 3, len(s) - 1):
            r = s[k:] + s[:k]
            out.append(case(
                f"identity/circular-{name}-rot{k}", "identity", 1,
                f"the same molecule rotated by {k}; cdseguid must not change",
                {"topology": "circular", "sequence": r},
                {},
                {"cdseguid": expected},
                {"tool": "seguid", "version": "0.2.1"},
            ))
        # ...and read from the other strand.
        out.append(case(
            f"identity/circular-{name}-revcomp", "identity", 1,
            "the same molecule read from the other strand",
            {"topology": "circular", "sequence": rc(s)},
            {},
            {"cdseguid": expected},
            {"tool": "seguid", "version": "0.2.1"},
        ))
        # Linear form, for contrast: strand invariant, not rotation invariant.
        out.append(case(
            f"identity/linear-{name}", "identity", 2,
            "ldseguid of the same sequence taken as linear",
            {"topology": "linear", "sequence": s},
            {},
            {"ldseguid": ldseguid(s, rc(s)), "lsseguid": lsseguid(s)},
            {"tool": "seguid", "version": "0.2.1"},
        ))
    return out


# ---------------------------------------------------------------------------
# digest: where the origin bugs live
# ---------------------------------------------------------------------------

def cut_positions(seq, enzyme_name, circular):
    """Biopython's answer. 1-based index of the base 3' of the top-strand nick."""
    enz = getattr(Restriction, enzyme_name)
    return sorted(enz.search(Seq(seq), linear=not circular))


def digest_cases():
    out = []

    # A construct with a known multiple cloning site, so several enzymes have
    # exactly one site and the answers are easy to check by eye.
    mcs = "GAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGTCGACCTGCAGGCATGCAAGCTT"
    backbone = rand_seq(1200)
    plasmid = backbone[:600] + mcs + backbone[600:]

    for enz in ENZYMES:
        for circular in (True, False):
            pos = cut_positions(plasmid, enz, circular)
            topo = "circular" if circular else "linear"
            out.append(case(
                f"digest/mcs-{enz}-{topo}", "digest", 1,
                f"{enz} on a {topo} construct carrying a standard MCS",
                {"topology": topo, "sequence": plasmid},
                {"enzyme": enz},
                {"cut_positions": pos, "cut_count": len(pos)},
                {"tool": "biopython", "version": "1.87"},
            ))

    # Tier 1: a site placed deliberately across the origin. A tool that scans
    # the sequence as a string, without wrapping, reports a non-cutter here --
    # and a non-cutter is exactly the answer that makes someone order the wrong
    # enzyme and lose a week.
    for enz in ["EcoRI", "BamHI", "HindIII", "NotI", "AscI", "PacI"]:
        site = str(getattr(Restriction, enz).site)
        for split in range(1, len(site)):
            head, tail = site[:split], site[split:]
            filler = rand_seq(300)
            # tail ... filler ... head  =>  reads as the site across the join
            seq = tail + filler + head
            pos_c = cut_positions(seq, enz, True)
            pos_l = cut_positions(seq, enz, False)
            out.append(case(
                f"digest/origin-{enz}-split{split}", "digest", 1,
                f"{enz} site split {split}/{len(site) - split} across the origin; "
                f"circular has {len(pos_c)} site(s), linear has {len(pos_l)}",
                {"topology": "circular", "sequence": seq},
                {"enzyme": enz},
                {"cut_positions": pos_c, "cut_count": len(pos_c)},
                {"tool": "biopython", "version": "1.87"},
            ))
            out.append(case(
                f"digest/origin-{enz}-split{split}-linear", "digest", 1,
                "the same sequence taken as linear: the site must NOT be found",
                {"topology": "linear", "sequence": seq},
                {"enzyme": enz},
                {"cut_positions": pos_l, "cut_count": len(pos_l)},
                {"tool": "biopython", "version": "1.87"},
            ))

    # Isoschizomers: same recognition site, different cut position. Getting
    # these the same way round is a silent, expensive class of error.
    iso = "AAAACCCGGGTTTT"
    for enz in ("SmaI", "XmaI"):
        pos = cut_positions(iso, enz, False)
        out.append(case(
            f"digest/isoschizomer-{enz}", "digest", 1,
            f"{enz} and its isoschizomer share CCCGGG but cut differently",
            {"topology": "linear", "sequence": iso},
            {"enzyme": enz},
            {"cut_positions": pos, "cut_count": len(pos)},
            {"tool": "biopython", "version": "1.87"},
        ))

    # Tandem and overlapping sites, where naive scanners double-count or skip.
    for label, seq in [
        ("tandem", "AAA" + "GAATTC" * 4 + "AAA"),
        ("adjacent", "AAAGAATTCGAATTCAAA"),
        ("overlapping-dam", "AAAGGATCCGGATCCAAA"),
    ]:
        for enz in ("EcoRI", "BamHI"):
            pos = cut_positions(seq, enz, False)
            out.append(case(
                f"digest/{label}-{enz}", "digest", 1,
                f"{enz} on {label} sites",
                {"topology": "linear", "sequence": seq},
                {"enzyme": enz},
                {"cut_positions": pos, "cut_count": len(pos)},
                {"tool": "biopython", "version": "1.87"},
            ))

    # Non-cutters, stated explicitly. "No sites" must be a positive answer,
    # not a silent empty result.
    nocut = "AAAATTTTAAAATTTT" * 5
    for enz in ("EcoRI", "NotI", "AscI"):
        pos = cut_positions(nocut, enz, True)
        assert pos == [], f"{enz} unexpectedly cuts the non-cutter fixture"
        out.append(case(
            f"digest/noncutter-{enz}", "digest", 1,
            f"{enz} does not cut this sequence; the answer is zero, not an error",
            {"topology": "circular", "sequence": nocut},
            {"enzyme": enz},
            {"cut_positions": [], "cut_count": 0},
            {"tool": "biopython", "version": "1.87"},
        ))
    return out


# ---------------------------------------------------------------------------
# pcr and assembly: pydna is the oracle
# ---------------------------------------------------------------------------

def pcr_cases():
    """Cases Polylinker cannot yet answer. Included on purpose.

    The bench describes what a plasmid editor should get right, not what this
    one currently implements. Publishing a pass rate that omits the unimplemented
    parts would be marketing rather than measurement.
    """
    out = []
    try:
        from pydna.dseqrecord import Dseqrecord
        from pydna.amplify import pcr
    except ImportError:
        print("  (pydna unavailable; skipping pcr cases)", file=sys.stderr)
        return out

    for i in range(6):
        template = rand_seq(800)
        start, length = 100 + i * 40, 300
        fwd = template[start:start + 22]
        rev = rc(template[start + length - 22:start + length])
        try:
            product = pcr(fwd, rev, Dseqrecord(template))
            p = str(product.seq).upper()
        except Exception as e:
            print(f"  (pcr case {i} skipped: {e})", file=sys.stderr)
            continue
        out.append(case(
            f"pcr/linear-template-{i}", "pcr", 2,
            "amplify an internal region of a linear template with exact-match primers",
            {"topology": "linear", "sequence": template},
            {"forward_primer": fwd, "reverse_primer": rev},
            {"product_length": len(p), "ldseguid": ldseguid(p, rc(p))},
            {"tool": "pydna", "version": "5.5.16"},
        ))
    return out


def assembly_cases():
    out = []
    try:
        from pydna.dseqrecord import Dseqrecord
        from pydna.assembly2 import Assembly
    except ImportError:
        try:
            from pydna.dseqrecord import Dseqrecord
            from pydna.assembly import Assembly
        except ImportError:
            print("  (pydna unavailable; skipping assembly cases)", file=sys.stderr)
            return out

    # Two fragments sharing terminal homology, circularised -- the Gibson shape.
    for i in range(5):
        homology_a = rand_seq(30)
        homology_b = rand_seq(30)
        middle_a = rand_seq(200)
        middle_b = rand_seq(250)
        frag1 = homology_a + middle_a + homology_b
        frag2 = homology_b + middle_b + homology_a
        try:
            asm = Assembly([Dseqrecord(frag1), Dseqrecord(frag2)], limit=25)
            circles = asm.assemble_circular()
            if not circles:
                continue
            prod = circles[0]
            s = str(prod.seq).upper()
            expected = cdseguid(s, rc(s))
        except Exception as e:
            print(f"  (assembly case {i} skipped: {e})", file=sys.stderr)
            continue
        out.append(case(
            f"assembly/gibson-two-fragment-{i}", "assembly", 1,
            "circularise two fragments sharing 30 bp terminal homology at both ends",
            {"fragments": [frag1, frag2], "topology": "circular"},
            {"method": "homologous", "min_homology": 25},
            {"cdseguid": expected, "length": len(s)},
            {"tool": "pydna", "version": "5.5.16"},
        ))
    return out


def main():
    cases = []
    cases += identity_cases()
    cases += digest_cases()
    cases += pcr_cases()
    cases += assembly_cases()

    by_op = {}
    for c in cases:
        by_op[c["operation"]] = by_op.get(c["operation"], 0) + 1

    doc = {
        "name": "polylinker-bench",
        "version": BENCH_VERSION,
        "licence": "CC0-1.0",
        "description": (
            "A truth set for plasmid operations. Every expected value is "
            "produced by an independent tool, never by Polylinker. All "
            "sequences are synthetic and redistributable."
        ),
        "oracles": {
            "identity": "seguid 0.2.1",
            "digest": "Biopython 1.87 (Bio.Restriction)",
            "pcr": "pydna 5.5.16",
            "assembly": "pydna 5.5.16",
        },
        "conventions": {
            "cut_positions": (
                "1-based index of the base immediately 3' of the nick on the "
                "top strand, as Bio.Restriction reports it"
            ),
            "coordinates": "1-based inclusive",
            "checksums": "SEGUID v2 long form, including the prefix",
        },
        "hazard_tiers": {
            "1": "silent, expensive, hard to notice at the bench",
            "2": "wrong but caught quickly",
            "3": "approximate by nature",
        },
        "counts": by_op,
        "cases": cases,
    }
    json.dump(doc, sys.stdout, indent=1)
    print(file=sys.stdout)
    print(f"generated {len(cases)} cases: " +
          ", ".join(f"{k} {v}" for k, v in sorted(by_op.items())), file=sys.stderr)


if __name__ == "__main__":
    main()
