//! Restriction sites added to a primer's 5' end.
//!
//! A restriction site added to a primer **is a tail**, in exactly
//! `pl-primer`'s sense: 5' of the footprint, pairing with nothing, contributing
//! nothing to Tm. No new machinery is needed for the concept, only for the
//! three checks that make it safe.
//!
//! # The tail is not part of the Tm, and the report says both numbers
//!
//! In cycle 1 only the footprint anneals, so the annealing temperature comes
//! from the footprint's Tm. From cycle 3 onward the pool contains strands whose
//! ends are the complement of the whole oligo, tail included, so the
//! full-length oligo anneals and Ta rises — which is why the standard protocol
//! runs a few cycles low and the rest high. Both temperatures are reported,
//! named apart, and the full-length one is never labelled "Tm" and never drives
//! the early cycles. It falls straight out of the footprint/tail split and
//! almost no competing tool reports it.
//!
//! # In frame is not offered, and silence would imply it was
//!
//! There is no in-frame mode. Getting one right needs the user's frame, whether
//! the fusion is N- or C-terminal, whether the native start and stop are kept,
//! and **the vector's reading frame at the insertion site** — which means
//! knowing the vector, not just the insert. A tool that guesses the last of
//! those and silently inserts two bases produces a construct that expresses a
//! frameshifted protein, sequences cleanly, and looks correct on every map.
//! That is strictly worse than not offering the feature.
//!
//! So [`Tail::frame_note`] states the arithmetic beside every tail, and it is
//! most emphatic in the case a user will assume is safe: a tail length
//! divisible by three is **not** evidence that a fusion is in frame.
//!
//! # The spacer, and a table this repository will not ship
//!
//! Most restriction enzymes cut poorly within a few bases of a fragment
//! terminus. The phenomenon is published — Kaufman & Evans (1990)
//! BioTechniques 9:304 and Moreira & Noren (1995) BioTechniques 19:56
//! established that cleavage near a terminus is inefficient and
//! enzyme-dependent — and per-enzyme requirements have been measured and
//! tabulated by enzyme manufacturers.
//!
//! **That table is not reproduced here, and there is no default spacer.** The
//! licence probe (2026-07-29) could not retrieve the operative sentence from
//! the source itself: both the guideline page and the terms-of-use page
//! returned HTTP 403 with no body. `features/SOURCING.md`'s rule governs — "I
//! found no licence" is not "there is no licence", and an unretrievable licence
//! is a hold rather than a permission. The table also has no independent open
//! leg the way `pl-enzymes`' sites (standard published references, cross-checked
//! against Biopython's BSD-3 `Bio.Restriction`) and `methylation.rs` (REBASE
//! `damlist`) do: it is a dataset one manufacturer generated by its own
//! experiments, and re-typing somebody's measurements does not make them an
//! independent derivation.
//!
//! What is done instead: cite the phenomenon, warn when a site is added with no
//! spacer ([`NO_SPACER_WARNING`]), let the user supply their own bases, and
//! validate whatever they supply.

use crate::params::Tailspec;
use pl_core::iupac::{find_all, is_palindrome_masks, reverse_complement};
use pl_enzymes::Enzyme;

/// Printed whenever a site is added with nothing 5' of it.
///
/// A warning rather than a refusal: the tool is not predicting the cut, and
/// refusing an ordinary, widely-used design because a number is not shippable
/// would be worse than saying so.
pub const NO_SPACER_WARNING: &str = "\
the site sits at the very end of the product with no bases 5' of it. Many enzymes cut \
such an end poorly or not at all, and how many extra bases each one needs has been \
measured and published by enzyme manufacturers. Polylinker does not ship that table \
(see the tail module's licence note) and is not predicting the cut -- add --spacer if \
in doubt, and check your enzyme's own supplier data before ordering.";

/// A 5' tail: whatever the user asked for, then the site.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Tail {
    /// The whole tail, 5'→3'. `spacer` then `enzyme.site`.
    pub bases: Vec<u8>,
    pub spacer: Vec<u8>,
    pub enzyme: &'static Enzyme,
}

impl Tail {
    /// Build, or say why the enzyme cannot be used as a tail.
    pub fn build(spec: &Tailspec) -> Result<Tail, crate::DesignError> {
        let site = spec.enzyme.site.as_bytes();
        // An N in the site has no single oligo to write down, and a tail is
        // real DNA that has to be ordered. Refusing beats picking a base.
        if !site
            .iter()
            .all(|b| matches!(b.to_ascii_uppercase(), b'A' | b'C' | b'G' | b'T'))
        {
            return Err(crate::DesignError::AmbiguousSite {
                enzyme: spec.enzyme.name,
                site: spec.enzyme.site,
            });
        }
        let mut bases = spec.spacer.to_ascii_uppercase();
        bases.extend_from_slice(&site.to_ascii_uppercase());
        Ok(Tail {
            bases,
            spacer: spec.spacer.to_ascii_uppercase(),
            enzyme: spec.enzyme,
        })
    }

    pub fn len(&self) -> usize {
        self.bases.len()
    }
    pub fn is_empty(&self) -> bool {
        self.bases.is_empty()
    }
    /// Where the site starts inside the tail, 0-based.
    pub fn site_offset(&self) -> usize {
        self.spacer.len()
    }

    /// The sentence that goes beside this tail, in the case that matters most.
    pub fn frame_note(&self) -> String {
        let n = self.len();
        if n % 3 == 0 {
            format!(
                "this tail adds {n} nt to the 5' end of the product. {n} is divisible by 3, \
                 but that does not make a fusion in frame: frame depends on the vector's \
                 reading frame at the insertion site, which Polylinker does not know. If you \
                 are making a fusion protein, check the frame yourself."
            )
        } else {
            format!(
                "this tail adds {n} nt to the 5' end of the product. If you are cloning in \
                 frame, this shifts the reading frame."
            )
        }
    }
}

/// A recognition site found somewhere it was not put.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InternalSite {
    /// The enzyme itself, not just its name: [`SiteClash::locate`] needs the
    /// site's length to tell a site inside a tail from one straddling the seam
    /// between the tail and the template, and those have different remedies.
    pub enzyme: &'static Enzyme,
    /// 1-based position in the product.
    pub position: u64,
    /// `+` when the site reads on the product's top strand, `-` on the bottom.
    pub strand: &'static str,
}

/// Where an unintended site sits, expressed in coordinates the user has.
///
/// [`InternalSite::position`] is a position in the *product*, which is a
/// molecule that does not exist yet and whose numbering depends on the tail
/// lengths. Nobody can act on that. The template coordinate is the one they can
/// look at on their own map, so the translation happens once, here, rather than
/// in the head of whoever reads the refusal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClashAt {
    /// 1-based coordinate on the template that was designed against.
    Template(u64),
    /// Wholly inside a tail this design added: `"forward"` or `"reverse"`.
    /// This is the spacer-carries-the-site case, which no scan of the template
    /// alone can see, and it is the user's own bases rather than their
    /// molecule's.
    Tail(&'static str),
    /// Across the seam between a tail and the template, `"forward"` or
    /// `"reverse"`.
    ///
    /// Its own case because the remedy is different from either neighbour's
    /// and because it is the one a user will not believe without being told:
    /// the site exists in neither the tail nor the template, only in the
    /// product. Measured: `--add-5 ClaI` with no spacer against a template
    /// whose span begins `CGAT` makes `ATCGAT|CGAT…`, and the second ATCGAT
    /// starts inside the tail and ends inside the template. Classifying it by
    /// its start alone called it a tail site and sent the user to `--spacer`,
    /// which cannot fix it.
    Junction(&'static str),
}

/// One unintended site, ready to be printed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SiteClash {
    pub enzyme: &'static str,
    /// `+` when the site reads on the plus strand, `-` on the minus.
    pub strand: &'static str,
    pub at: ClashAt,
}

impl SiteClash {
    /// Translate a product position into the frame the user is looking at.
    ///
    /// `span_start` is the unrolled 0-based plus-strand coordinate of the
    /// product's first template base — the forward footprint's outer end.
    pub fn locate(
        site: &InternalSite,
        ftail_len: usize,
        rtail_len: usize,
        product_len: usize,
        span_start: i64,
        n: u64,
    ) -> SiteClash {
        let lo = site.position as usize - 1;
        let hi = lo + site.enzyme.site.len(); // exclusive
        let span_end = product_len - rtail_len; // exclusive
        let at = if hi <= ftail_len {
            ClashAt::Tail("forward")
        } else if lo >= span_end {
            ClashAt::Tail("reverse")
        } else if lo < ftail_len {
            ClashAt::Junction("forward")
        } else if hi > span_end {
            ClashAt::Junction("reverse")
        } else {
            let unrolled = span_start + (lo - ftail_len) as i64;
            ClashAt::Template(unrolled.rem_euclid(n as i64) as u64 + 1)
        };
        SiteClash {
            enzyme: site.enzyme.name,
            strand: site.strand,
            at,
        }
    }

    pub fn render(&self) -> String {
        match self.at {
            ClashAt::Template(p) => format!(
                "{} also reads at {p} on the {} strand of this template, inside the product",
                self.enzyme, self.strand
            ),
            ClashAt::Tail(which) => format!(
                "{} reads a second time inside the {which} tail itself, on the {} strand -- \
                 the spacer and the site together spell it. No scan of the template can see \
                 this one; change --spacer",
                self.enzyme, self.strand
            ),
            ClashAt::Junction(which) => format!(
                "the {which} tail and the template bases next to it spell a second {} site \
                 across the seam, on the {} strand. It is in neither the tail nor the \
                 template alone, so only the finished product has it -- a --spacer whose \
                 bases break the seam fixes it, and moving the primer by a base or two also \
                 does",
                self.enzyme, self.strand
            ),
        }
    }
}

/// Every occurrence of an enzyme's site in `product` other than the two that
/// were engineered.
///
/// # Why `find_all` and not `cut_positions`
///
/// The question is "is there an unintended site", not "will it cut".
/// `pl_enzymes::cut_sites` drops a match whose nicks fall off the end of a
/// linear molecule — the `bond_exists` guard — so with a short spacer a
/// designed Type IIS site can vanish from the cut list while the recognition
/// sequence is plainly there. Two different questions, two different calls.
///
/// # Both strands, by construction rather than by a second hand-rolled scan
///
/// For a palindromic Type IIP enzyme the forward scan already finds every
/// bottom-strand site, because the site equals its own reverse complement. For
/// a non-palindromic enzyme the explicit reverse-complement scan is required —
/// the exact asymmetry `pl_enzymes::cut_sites` documents, where scanning
/// forward alone lost three of eight BsaI cuts on a 180 kb contig. Do not
/// assume palindromy; branch on `is_palindrome_masks` as that function does.
///
/// # The engineered positions are known, not inferred
///
/// The tail records where it put the site, so the forward site is at
/// `spacer_len + 1` and the reverse one at
/// `product.len() - spacer_len - site_len + 1`. Everything else is internal.
///
/// # Methylation is deliberately not applied
///
/// A PCR product is synthesised from dNTPs in vitro and is therefore
/// **unmethylated**. Running `pl_enzymes::methylation::site_effect` over it
/// would spuriously reject ClaI, XbaI and the rest of the Dam-blocked set for a
/// molecule they cut perfectly. Methylation is a question about the *vector*,
/// which normally came out of a dam⁺ dcm⁺ strain, and is asked there.
pub fn internal_sites(
    product: &[u8],
    enzyme: &'static Enzyme,
    engineered: &[u64],
) -> Vec<InternalSite> {
    let site = enzyme.site.as_bytes();
    let mut hits: Vec<(u64, &'static str)> = find_all(site, product, false)
        .into_iter()
        .map(|p| (p, "+"))
        .collect();
    if !is_palindrome_masks(site) {
        let rc = reverse_complement(site);
        hits.extend(find_all(&rc, product, false).into_iter().map(|p| (p, "-")));
    }
    hits.sort_unstable();
    hits.dedup();
    hits.into_iter()
        .filter(|(p, _)| !engineered.contains(p))
        .map(|(position, strand)| InternalSite {
            enzyme,
            position,
            strand,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::params::Tailspec;

    fn ecori() -> &'static Enzyme {
        pl_enzymes::by_name("EcoRI").unwrap()
    }

    #[test]
    fn a_tail_is_the_spacer_then_the_site() {
        let t = Tail::build(&Tailspec {
            enzyme: ecori(),
            spacer: b"ggatcc".to_vec(),
        })
        .unwrap();
        assert_eq!(t.bases, b"GGATCCGAATTC".to_vec());
        assert_eq!(t.site_offset(), 6);
        assert_eq!(t.len(), 12);
    }

    #[test]
    fn an_enzyme_whose_site_carries_an_n_is_refused_rather_than_guessed_at() {
        // Constructed rather than looked up, because **no shipped enzyme has an
        // ambiguous site** -- `pl-enzymes` pins that. So this guard cannot fire
        // on today's table and exists for a user-supplied set; a test that
        // reached for `by_name` would be asserting nothing. Same shape as
        // pl-enzymes' own interrupted-palindrome test, and the same reason.
        static BSTXI: pl_enzymes::Enzyme = pl_enzymes::Enzyme {
            name: "BstXI",
            site: "CCANNNNNNTGG",
            fst5: 8,
            ovhg: 4,
        };
        assert!(
            pl_enzymes::ENZYMES.iter().all(|e| !e.site.contains('N')),
            "if an ambiguous site ever ships, use it here instead"
        );
        assert!(matches!(
            Tail::build(&Tailspec {
                enzyme: &BSTXI,
                spacer: Vec::new()
            }),
            Err(crate::DesignError::AmbiguousSite { .. })
        ));
        // The control: an unambiguous site of the same length is accepted.
        assert!(Tail::build(&Tailspec {
            enzyme: ecori(),
            spacer: Vec::new()
        })
        .is_ok());
    }

    #[test]
    fn the_frame_note_is_loudest_where_a_user_would_assume_it_is_safe() {
        let six = Tail::build(&Tailspec {
            enzyme: ecori(),
            spacer: Vec::new(),
        })
        .unwrap();
        assert_eq!(six.len() % 3, 0);
        let note = six.frame_note();
        assert!(note.contains("divisible by 3"), "{note}");
        assert!(note.contains("does not make a fusion in frame"), "{note}");

        let seven = Tail::build(&Tailspec {
            enzyme: ecori(),
            spacer: b"A".to_vec(),
        })
        .unwrap();
        assert!(seven.frame_note().contains("shifts the reading frame"));
    }

    #[test]
    fn an_engineered_site_is_not_reported_and_an_extra_one_is() {
        // A product with EcoRI at both ends -- as designed -- and a third copy
        // in the middle, which would cut the insert in three.
        let mut product = b"GAATTC".to_vec();
        product.extend_from_slice(b"ACGTACGTACGT");
        product.extend_from_slice(b"GAATTC");
        product.extend_from_slice(b"ACGTACGTACGT");
        product.extend_from_slice(b"GAATTC");
        let end = product.len() as u64 - 6 + 1;
        let hits = internal_sites(&product, ecori(), &[1, end]);
        assert_eq!(hits.len(), 1, "{hits:?}");
        assert_eq!(hits[0].position, 19);
    }

    /// PROVEN TO FAIL: with the reverse-complement scan skipped, this finds
    /// nothing where a BsaI site plainly sits - the product reported as clean
    /// for an enzyme that cuts it.
    #[test]
    fn a_non_palindromic_site_is_found_on_the_bottom_strand_too() {
        // The asymmetry `pl_enzymes::cut_sites` documents: scanning forward
        // alone loses minus-strand sites of a Type IIS enzyme, and here that
        // would mean reporting a product as clean when the enzyme cuts it.
        let bsai = pl_enzymes::by_name("BsaI").expect("BsaI ships");
        assert!(!is_palindrome_masks(bsai.site.as_bytes()));
        let rc = reverse_complement(bsai.site.as_bytes());
        let mut product = b"ACGTACGTACGTACGT".to_vec();
        product.extend_from_slice(&rc);
        product.extend_from_slice(b"ACGTACGTACGTACGT");
        let hits = internal_sites(&product, bsai, &[]);
        assert_eq!(hits.len(), 1, "{hits:?}");
        assert_eq!(hits[0].strand, "-");
    }
}
