//! Restriction sites added to a primer's 5' end.
//!
//! A restriction site added to a primer **is a tail**, in exactly
//! `pl-primer`'s sense: 5' of the footprint, pairing with nothing, contributing
//! nothing to Tm. No new machinery is needed for the concept, only for the
//! checks that make it safe: the internal-site scan, the no-spacer warning, the
//! frame note — and the whole-oligo structure numbers, which are the one the
//! list here used to omit.
//!
//! # A tail is not in the Tm, and it IS in the fold
//!
//! Those are different claims and the code made only the first. `oligo::evaluate`
//! screens hairpins and dimers on the **footprint**, because that is all it has
//! when a candidate is enumerated; the tail is built later, in `pair::run`. But
//! a hairpin is not a Tm — it is a property of the molecule that is ordered, and
//! the tail is part of that molecule. Measured over 40 random 4 kb templates
//! with `--add-5 NotI --add-3 XhoI --spacer TTGGCA`: 166 of 350 ordered oligos
//! carry a whole-oligo hairpin at or past the −5.0 kcal/mol gate the same run
//! applied to footprints, the worst at −9.7 with a 6 bp stem pairing spacer and
//! site bases against footprint bases, in a run that discarded 56 candidates for
//! a hairpin at or below −5.0. Gating on it would change which pairs exist, so
//! what is done instead is what was done for Tm: report both numbers, name which
//! is which, and say so in [`crate::Report::warnings`]. See
//! [`crate::Primer::hairpin_full`].
//!
//! # The tail is not part of the Tm, and the report says both numbers
//!
//! In cycle 1 only the footprint anneals, so the annealing temperature comes
//! from the footprint's Tm. From cycle 3 onward the pool contains strands whose
//! ends are the complement of the whole oligo, tail included, so the
//! full-length oligo anneals and Ta rises — which is why the standard protocol
//! runs a few cycles low and the rest high. Both temperatures are reported,
//! named apart, and the full-length one is never labelled "Tm" and never drives
//! the early cycles. It falls straight out of the footprint/tail split and
//! almost no competing tool reports it.
//!
//! # In frame is not offered, and silence would imply it was
//!
//! There is no in-frame mode. Getting one right needs the user's frame, whether
//! the fusion is N- or C-terminal, whether the native start and stop are kept,
//! and **the vector's reading frame at the insertion site** — which means
//! knowing the vector, not just the insert. A tool that guesses the last of
//! those and silently inserts two bases produces a construct that expresses a
//! frameshifted protein, sequences cleanly, and looks correct on every map.
//! That is strictly worse than not offering the feature.
//!
//! So [`Tail::frame_note`] states the arithmetic beside every tail, and it is
//! most emphatic in the case a user will assume is safe: a tail length
//! divisible by three is **not** evidence that a fusion is in frame.
//!
//! # The spacer, and a table this repository will not ship
//!
//! Most restriction enzymes cut poorly within a few bases of a fragment
//! terminus. The phenomenon is published — Kaufman & Evans (1990)
//! BioTechniques 9:304 and Moreira & Noren (1995) BioTechniques 19:56
//! established that cleavage near a terminus is inefficient and
//! enzyme-dependent — and per-enzyme requirements have been measured and
//! tabulated by enzyme manufacturers.
//!
//! **That table is not reproduced here, and there is no default spacer.** The
//! licence probe (2026-07-29) could not retrieve the operative sentence from
//! the source itself: both the guideline page and the terms-of-use page
//! returned HTTP 403 with no body. `features/SOURCING.md`'s rule governs — "I
//! found no licence" is not "there is no licence", and an unretrievable licence
//! is a hold rather than a permission. The table also has no independent open
//! leg the way `pl-enzymes`' sites (standard published references, cross-checked
//! against Biopython's BSD-3 `Bio.Restriction`) and `methylation.rs` (REBASE
//! `damlist`) do: it is a dataset one manufacturer generated by its own
//! experiments, and re-typing somebody's measurements does not make them an
//! independent derivation.
//!
//! What is done instead: cite the phenomenon, warn when a site is added with no
//! spacer ([`NO_SPACER_WARNING`]), let the user supply their own bases, and
//! validate whatever they supply.

use crate::params::Tailspec;
use pl_core::iupac::{find_all, is_palindrome_masks, reverse_complement};
use pl_enzymes::Enzyme;

/// Printed whenever a site is added with nothing 5' of it.
///
/// A warning rather than a refusal: the tool is not predicting the cut, and
/// refusing an ordinary, widely-used design because a number is not shippable
/// would be worse than saying so.
pub const NO_SPACER_WARNING: &str = "\
the site sits at the very end of the product with no bases 5' of it. Many enzymes cut \
such an end poorly or not at all, and how many extra bases each one needs has been \
measured and published by enzyme manufacturers. Polylinker does not ship that table \
(see the tail module's licence note) and is not predicting the cut -- add --spacer if \
in doubt, and check your enzyme's own supplier data before ordering.";

/// A 5' tail: whatever the user asked for, then the site.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Tail {
    /// The whole tail, 5'→3'. `spacer` then `enzyme.site`.
    pub bases: Vec<u8>,
    pub spacer: Vec<u8>,
    pub enzyme: &'static Enzyme,
}

impl Tail {
    /// Build, or say why the enzyme cannot be used as a tail.
    pub fn build(spec: &Tailspec) -> Result<Tail, crate::DesignError> {
        let site = spec.enzyme.site.as_bytes();
        // An N in the site has no single oligo to write down, and a tail is
        // real DNA that has to be ordered. Refusing beats picking a base.
        if !site
            .iter()
            .all(|b| matches!(b.to_ascii_uppercase(), b'A' | b'C' | b'G' | b'T'))
        {
            return Err(crate::DesignError::AmbiguousSite {
                enzyme: spec.enzyme.name,
                site: spec.enzyme.site,
            });
        }
        let mut bases = spec.spacer.to_ascii_uppercase();
        bases.extend_from_slice(&site.to_ascii_uppercase());
        Ok(Tail {
            bases,
            spacer: spec.spacer.to_ascii_uppercase(),
            enzyme: spec.enzyme,
        })
    }

    pub fn len(&self) -> usize {
        self.bases.len()
    }
    pub fn is_empty(&self) -> bool {
        self.bases.is_empty()
    }
    /// Where the site starts inside the tail, 0-based.
    pub fn site_offset(&self) -> usize {
        self.spacer.len()
    }

    /// The sentence that goes beside this tail, in the case that matters most.
    ///
    /// `which` is `"forward"` or `"reverse"`, because the two tails land at
    /// opposite ends of the product's top strand and the note used to say "the
    /// 5' end of the product" for both.
    ///
    /// # Two lengths, and the spacer is not in the one that matters
    ///
    /// The note used to do its arithmetic on `self.len()` — spacer plus site —
    /// and then assert outright "this shifts the reading frame" whenever that
    /// was not a multiple of three. The spacer is 5' of the recognition site,
    /// therefore 5' of the cut, therefore discarded on digestion. Proved with
    /// this project's own `pl digest`: tails of 6, 7 and 8 nt (no spacer,
    /// `--spacer A`, `--spacer GG`, EcoRI + HindIII) yield a byte-identical
    /// 433 nt insert, and the tool called two of those three a frameshift and
    /// one not. What sits between the vector's frame and the first template base
    /// after ligation is the **regenerated site**, so the frame-relevant length
    /// is `enzyme.site.len()` and the spacer contributes exactly zero — for any
    /// spacer, of any length, with any enzyme.
    ///
    /// So both lengths are stated, apart, and neither branch makes an
    /// affirmative frame claim: an unqualified "this shifts the reading frame"
    /// about a construct that is frame-neutral invites a user to compensate, and
    /// compensating by trimming a footprint introduces the real +1 the module
    /// doc calls "strictly worse than not offering the feature".
    pub fn frame_note(&self, which: &str) -> String {
        let n = self.len();
        let site = self.enzyme.site.len();
        let end = if which == "reverse" {
            "3' end of the product's top strand"
        } else {
            "5' end of the product's top strand"
        };
        format!(
            "this tail adds {n} nt to the {end} of the PCR product ({} nt of spacer and the \
             {site} nt {} site). If you digest and ligate, the spacer is cut away with the \
             small fragment and what separates the vector from the first template base is \
             the regenerated {site} nt site -- so {site}, not {n}, is the length that moves \
             the frame there. {} Neither number makes a fusion in frame on its own: frame \
             depends on the vector's reading frame at the insertion site, which Polylinker \
             does not know. If you are making a fusion protein, check the frame yourself.",
            self.spacer.len(),
            self.enzyme.name,
            if site % 3 == 0 {
                format!("{site} is divisible by 3.")
            } else {
                format!(
                    "{site} is not divisible by 3, so that junction shifts by {}.",
                    site % 3
                )
            }
        )
    }
}

/// A recognition site found somewhere it was not put.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InternalSite {
    /// The enzyme itself, not just its name: [`SiteClash::locate`] needs the
    /// site's length to tell a site inside a tail from one straddling the seam
    /// between the tail and the template, and those have different remedies.
    pub enzyme: &'static Enzyme,
    /// 1-based position in the product.
    pub position: u64,
    /// `+` when the site reads on the product's top strand, `-` on the bottom.
    pub strand: &'static str,
}

/// Where an unintended site sits, expressed in coordinates the user has.
///
/// [`InternalSite::position`] is a position in the *product*, which is a
/// molecule that does not exist yet and whose numbering depends on the tail
/// lengths. Nobody can act on that. The template coordinate is the one they can
/// look at on their own map, so the translation happens once, here, rather than
/// in the head of whoever reads the refusal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClashAt {
    /// 1-based coordinate on the template that was designed against.
    Template(u64),
    /// Wholly inside a tail this design added: `"forward"` or `"reverse"`.
    /// This is the spacer-carries-the-site case, which no scan of the template
    /// alone can see, and it is the user's own bases rather than their
    /// molecule's.
    Tail(&'static str),
    /// Across the seam between a tail and the template, `"forward"` or
    /// `"reverse"`.
    ///
    /// Its own case because the remedy is different from either neighbour's
    /// and because it is the one a user will not believe without being told:
    /// the site exists in neither the tail nor the template, only in the
    /// product. Measured: `--add-5 ClaI` with no spacer against a template
    /// whose span begins `CGAT` makes `ATCGAT|CGAT…`, and the second ATCGAT
    /// starts inside the tail and ends inside the template. Classifying it by
    /// its start alone called it a tail site and sent the user to `--spacer`,
    /// which cannot fix it.
    Junction(&'static str),
}

/// One unintended site, ready to be printed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SiteClash {
    pub enzyme: &'static str,
    /// `+` when the site reads on the plus strand, `-` on the minus.
    pub strand: &'static str,
    pub at: ClashAt,
}

impl SiteClash {
    /// Translate a product position into the frame the user is looking at.
    ///
    /// `span_start` is the unrolled 0-based plus-strand coordinate of the
    /// product's first template base — the forward footprint's outer end.
    pub fn locate(
        site: &InternalSite,
        ftail_len: usize,
        rtail_len: usize,
        product_len: usize,
        span_start: i64,
        n: u64,
    ) -> SiteClash {
        let lo = site.position as usize - 1;
        let hi = lo + site.enzyme.site.len(); // exclusive
        let span_end = product_len - rtail_len; // exclusive
        let at = if hi <= ftail_len {
            ClashAt::Tail("forward")
        } else if lo >= span_end {
            ClashAt::Tail("reverse")
        } else if lo < ftail_len {
            ClashAt::Junction("forward")
        } else if hi > span_end {
            ClashAt::Junction("reverse")
        } else {
            let unrolled = span_start + (lo - ftail_len) as i64;
            ClashAt::Template(unrolled.rem_euclid(n as i64) as u64 + 1)
        };
        SiteClash {
            enzyme: site.enzyme.name,
            strand: site.strand,
            at,
        }
    }

    pub fn render(&self) -> String {
        match self.at {
            ClashAt::Template(p) => format!(
                "{} also reads at {p} on the {} strand of this template, inside the product",
                self.enzyme, self.strand
            ),
            ClashAt::Tail(which) => format!(
                "{} reads a second time inside the {which} tail itself, on the {} strand -- \
                 the spacer and the site together spell it. No scan of the template can see \
                 this one; change --spacer",
                self.enzyme, self.strand
            ),
            ClashAt::Junction(which) => format!(
                "the {which} tail and the template bases next to it spell a second {} site \
                 across the seam, on the {} strand. It is in neither the tail nor the \
                 template alone, so only the finished product has it -- a --spacer whose \
                 bases break the seam fixes it, and moving the primer by a base or two also \
                 does",
                self.enzyme, self.strand
            ),
        }
    }
}

/// Every occurrence of an enzyme's site in `product` other than the two that
/// were engineered.
///
/// # Why `find_all` and not `cut_positions`
///
/// The question is "is there an unintended site", not "will it cut".
/// `pl_enzymes::cut_sites` drops a match whose nicks fall off the end of a
/// linear molecule — the `bond_exists` guard — so with a short spacer a
/// designed Type IIS site can vanish from the cut list while the recognition
/// sequence is plainly there. Two different questions, two different calls.
///
/// # Both strands, by construction rather than by a second hand-rolled scan
///
/// For a palindromic Type IIP enzyme the forward scan already finds every
/// bottom-strand site, because the site equals its own reverse complement. For
/// a non-palindromic enzyme the explicit reverse-complement scan is required —
/// the exact asymmetry `pl_enzymes::cut_sites` documents, where scanning
/// forward alone lost three of eight BsaI cuts on a 180 kb contig. Do not
/// assume palindromy; branch on `is_palindrome_masks` as that function does.
///
/// # The engineered positions are known, not inferred
///
/// The tail records where it put the site, so the forward site is at
/// `spacer_len + 1` and the reverse one at
/// `product.len() - spacer_len - site_len + 1`. Everything else is internal.
///
/// # Methylation is deliberately not applied
///
/// A PCR product is synthesised from dNTPs in vitro and is therefore
/// **unmethylated**. Running `pl_enzymes::methylation::site_effect` over it
/// would spuriously reject ClaI, XbaI and the rest of the Dam-blocked set for a
/// molecule they cut perfectly. Methylation is a question about the *vector*,
/// which normally came out of a dam⁺ dcm⁺ strain, and is asked there.
pub fn internal_sites(
    product: &[u8],
    enzyme: &'static Enzyme,
    engineered: &[u64],
) -> Vec<InternalSite> {
    let site = enzyme.site.as_bytes();
    let mut hits: Vec<(u64, &'static str)> = find_all(site, product, false)
        .into_iter()
        .map(|p| (p, "+"))
        .collect();
    if !is_palindrome_masks(site) {
        let rc = reverse_complement(site);
        hits.extend(find_all(&rc, product, false).into_iter().map(|p| (p, "-")));
    }
    hits.sort_unstable();
    hits.dedup();
    hits.into_iter()
        .filter(|(p, _)| !engineered.contains(p))
        .map(|(position, strand)| InternalSite {
            enzyme,
            position,
            strand,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::params::Tailspec;

    fn ecori() -> &'static Enzyme {
        pl_enzymes::by_name("EcoRI").unwrap()
    }

    #[test]
    fn a_tail_is_the_spacer_then_the_site() {
        let t = Tail::build(&Tailspec {
            enzyme: ecori(),
            spacer: b"ggatcc".to_vec(),
        })
        .unwrap();
        assert_eq!(t.bases, b"GGATCCGAATTC".to_vec());
        assert_eq!(t.site_offset(), 6);
        assert_eq!(t.len(), 12);
    }

    #[test]
    fn an_enzyme_whose_site_carries_an_n_is_refused_rather_than_guessed_at() {
        // Constructed rather than looked up, because **no shipped enzyme has an
        // ambiguous site** -- `pl-enzymes` pins that. So this guard cannot fire
        // on today's table and exists for a user-supplied set; a test that
        // reached for `by_name` would be asserting nothing. Same shape as
        // pl-enzymes' own interrupted-palindrome test, and the same reason.
        static BSTXI: pl_enzymes::Enzyme = pl_enzymes::Enzyme {
            name: "BstXI",
            site: "CCANNNNNNTGG",
            fst5: 8,
            ovhg: 4,
        };
        assert!(
            pl_enzymes::ENZYMES.iter().all(|e| !e.site.contains('N')),
            "if an ambiguous site ever ships, use it here instead"
        );
        assert!(matches!(
            Tail::build(&Tailspec {
                enzyme: &BSTXI,
                spacer: Vec::new()
            }),
            Err(crate::DesignError::AmbiguousSite { .. })
        ));
        // The control: an unambiguous site of the same length is accepted.
        assert!(Tail::build(&Tailspec {
            enzyme: ecori(),
            spacer: Vec::new()
        })
        .is_ok());
    }

    /// The frame note reasons about the length the DIGEST leaves behind.
    ///
    /// PROVEN TO FAIL against the shipped `frame_note`, which did its modulo on
    /// `spacer + site` and then asserted "this shifts the reading frame"
    /// outright: `--spacer A` and `--spacer GG` on the same EcoRI design gave 7
    /// and 8, so both printed the affirmative frameshift claim, while `pl digest`
    /// on all three amplicons yields a byte-identical insert. The spacer is 5' of
    /// the site, therefore 5' of the cut, therefore not there afterwards.
    #[test]
    fn the_frame_note_reasons_about_the_site_the_digest_leaves_and_not_the_spacer() {
        let mk = |spacer: &[u8]| {
            Tail::build(&Tailspec {
                enzyme: ecori(),
                spacer: spacer.to_vec(),
            })
            .unwrap()
        };
        let (six, seven, eight) = (mk(b""), mk(b"A"), mk(b"GG"));
        assert_eq!((six.len(), seven.len(), eight.len()), (6, 7, 8));

        // All three regenerate the same 6 nt EcoRI site on ligation, so all
        // three make the same frame claim -- which is the point.
        for t in [&six, &seven, &eight] {
            let note = t.frame_note("forward");
            assert!(note.contains("6 nt EcoRI site"), "{note}");
            assert!(note.contains("6, not"), "{note}");
            assert!(note.contains("6 is divisible by 3"), "{note}");
            assert!(
                !note.contains("this shifts the reading frame"),
                "an affirmative frame claim about a construct that is frame-neutral: {note}"
            );
            assert!(note.contains("does not know"), "{note}");
        }
        // The tail lengths are still stated -- they are what the PCR product
        // gains, which is the number that matters for a blunt or Gibson clone.
        assert!(seven.frame_note("forward").contains("adds 7 nt"));
        assert!(eight.frame_note("forward").contains("adds 8 nt"));

        // An 8 nt site is where the site length really does shift the frame,
        // and the note says so about the site rather than about the tail.
        let fsei = pl_enzymes::by_name("FseI").expect("FseI ships");
        assert_eq!(fsei.site.len(), 8);
        let f = Tail::build(&Tailspec {
            enzyme: fsei,
            spacer: b"G".to_vec(),
        })
        .unwrap();
        assert_eq!(
            f.len(),
            9,
            "the tail is a multiple of 3 and the site is not"
        );
        let note = f.frame_note("forward");
        assert!(note.contains("8 is not divisible by 3"), "{note}");
        assert!(note.contains("shifts by 2"), "{note}");

        // And the two tails land at opposite ends of the product's top strand.
        assert!(six.frame_note("forward").contains("5' end of the product"));
        assert!(six.frame_note("reverse").contains("3' end of the product"));
    }

    #[test]
    fn an_engineered_site_is_not_reported_and_an_extra_one_is() {
        // A product with EcoRI at both ends -- as designed -- and a third copy
        // in the middle, which would cut the insert in three.
        let mut product = b"GAATTC".to_vec();
        product.extend_from_slice(b"ACGTACGTACGT");
        product.extend_from_slice(b"GAATTC");
        product.extend_from_slice(b"ACGTACGTACGT");
        product.extend_from_slice(b"GAATTC");
        let end = product.len() as u64 - 6 + 1;
        let hits = internal_sites(&product, ecori(), &[1, end]);
        assert_eq!(hits.len(), 1, "{hits:?}");
        assert_eq!(hits[0].position, 19);
    }

    /// PROVEN TO FAIL: with the reverse-complement scan skipped, this finds
    /// nothing where a BsaI site plainly sits - the product reported as clean
    /// for an enzyme that cuts it.
    #[test]
    fn a_non_palindromic_site_is_found_on_the_bottom_strand_too() {
        // The asymmetry `pl_enzymes::cut_sites` documents: scanning forward
        // alone loses minus-strand sites of a Type IIS enzyme, and here that
        // would mean reporting a product as clean when the enzyme cuts it.
        let bsai = pl_enzymes::by_name("BsaI").expect("BsaI ships");
        assert!(!is_palindrome_masks(bsai.site.as_bytes()));
        let rc = reverse_complement(bsai.site.as_bytes());
        let mut product = b"ACGTACGTACGTACGT".to_vec();
        product.extend_from_slice(&rc);
        product.extend_from_slice(b"ACGTACGTACGTACGT");
        let hits = internal_sites(&product, bsai, &[]);
        assert_eq!(hits.len(), 1, "{hits:?}");
        assert_eq!(hits[0].strand, "-");
    }
}
