"""Generate prototype/demo-construct.gb, the molecule the browser tool opens on load.

Committed as data rather than built in the page, so the page carries no
format-writing code of its own. Deterministic: same output every run.
"""

import os
import sys

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "prototype", "demo-construct.gb")

N = 3180


def mulberry32(seed):
    a = seed & 0xFFFFFFFF

    def rnd():
        nonlocal a
        a = (a + 0x6D2B79F5) & 0xFFFFFFFF
        t = a
        t = (t ^ (t >> 15)) * (t | 1) & 0xFFFFFFFF
        t ^= (t + ((t ^ (t >> 7)) * (t | 61) & 0xFFFFFFFF)) & 0xFFFFFFFF
        return ((t ^ (t >> 14)) & 0xFFFFFFFF) / 4294967296
    return rnd


def build_sequence():
    rnd = mulberry32(20260726)
    bases = "ACGT"
    arr = [bases[int(rnd() * 4) % 4] for _ in range(N)]

    def put(s, at):                       # `at` is 0-based
        for i, c in enumerate(s):
            arr[at + i] = c

    # A real multiple cloning site, so the enzyme panel has honest work to do.
    put("GAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGTCGACCTGCAGGCATGCAAGCTT", 1806)
    put("GCGGCCGC", 640)     # NotI
    put("CATATG", 1868)      # NdeI, at the start of the reporter
    put("ACTAGT", 2600)      # SpeI

    # Splice the primers in so they genuinely anneal. A 22-mer does not occur by
    # chance in 3.2 kb, so without this the primer panel would be empty and the
    # demo would misrepresent what the tool does.
    comp = {"A": "T", "C": "G", "G": "C", "T": "A"}
    put(PRIMERS[0][1], 1699)
    put("".join(comp[c] for c in reversed(PRIMERS[1][1])), 2299)
    return "".join(arr)


FEATURES = [
    # (key, start, end, reverse, label, colour, translated)
    ("rep_origin",   60,   648,  False, "ori",           "#3f6f9a", False),
    ("CDS",          700,  1560, False, "AmpR",          "#9a5b8c", True),
    ("promoter",     1570, 1674, False, "AmpR promoter", "#3f8f4f", False),
    ("promoter",     1740, 1786, False, "lac promoter",  "#3f8f4f", False),
    ("misc_feature", 1807, 1863, False, "MCS",           "#7d8a86", False),
    ("CDS",          1869, 2585, False, "reporter CDS",   "#9a5b8c", True),
    ("terminator",   2600, 2647, False, "T7 terminator", "#b0553f", False),
    ("CDS",          2700, 3120, True,  "KanR",          "#9a5b8c", True),
]

PRIMERS = [
    ("M13-fwd-like", "GTAAAACGACGGCCAGTGAATT"),
    ("seq-rev-demo", "CAGGAAACAGCTATGACCATG"),
]


def qualifier(key, value):
    pad = " " * 21
    raw = f'/{key}="{value}"'
    lines, line = [], pad
    for word in raw.split(" "):
        if len(line) + len(word) + 1 > 79 and line.strip():
            lines.append(line)
            line = pad
        line += ("" if line == pad else " ") + word
    if line.strip():
        lines.append(line)
    return "\n".join(lines)


def find_sites(seq, primer):
    """Forward and reverse-complement exact matches, 1-based inclusive."""
    comp = {"A": "T", "C": "G", "G": "C", "T": "A"}
    rc = "".join(comp[c] for c in reversed(primer))
    hits = []
    for probe, rev in ((primer, False), (rc, True)):
        start = 0
        while True:
            i = seq.find(probe, start)
            if i == -1:
                break
            hits.append((i + 1, i + len(probe), rev))
            start = i + 1
    return hits


def main():
    seq = build_sequence()
    out = []
    # Columns per the GenBank spec, matching `genbank::locus_line` in
    # crates/pl-fileio. This is a second, independent LOCUS writer, so it drifts
    # unless kept in step deliberately: it was emitting 76 characters while the
    # Rust writer emitted 75, and neither was the specified 79.
    #   13-28 name | 30-40 length | 42-43 bp | 45-47 ss-/ds- | 48-53 type
    #   56-63 topology | 65-67 division | 69-79 date
    out.append(
        f"LOCUS       {'demo-construct':<16} {N:>11} bp    DNA     "
        f"{'circular':<8} {'SYN':<3} 26-JUL-2026"
    )
    out.append("DEFINITION  Synthetic demo construct. Not a real plasmid.")
    out.append("ACCESSION   .")
    out.append("VERSION     .")
    out.append("KEYWORDS    .")
    out.append("SOURCE      synthetic DNA construct")
    out.append("  ORGANISM  synthetic DNA construct")
    out.append("COMMENT     Generated by tools/make-demo.py. Deterministic; edit the script,")
    out.append("            not this file.")
    out.append("FEATURES             Location/Qualifiers")
    out.append(f"     source          1..{N}")
    out.append(qualifier("organism", "synthetic DNA construct"))
    out.append(qualifier("mol_type", "other DNA"))

    for key, start, end, rev, label, color, translated in FEATURES:
        loc = f"complement({start}..{end})" if rev else f"{start}..{end}"
        out.append(f"     {key:<15} {loc}")
        out.append(qualifier("label", label))
        if translated:
            out.append(qualifier("codon_start", "1"))
        out.append(qualifier("ApEinfo_fwdcolor", color))
        out.append(qualifier("ApEinfo_revcolor", color))
        out.append(qualifier("note", f"color: {color}"))

    for name, primer in PRIMERS:
        for start, end, rev in find_sites(seq, primer):
            loc = f"complement({start}..{end})" if rev else f"{start}..{end}"
            out.append(f"     {'primer_bind':<15} {loc}")
            out.append(qualifier("label", name))
            out.append(qualifier("note", f"primer {primer}"))

    # Uppercase deliberately. GenBank convention is lowercase, but Polylinker
    # preserves case and treats lowercase as meaningful (soft-masked or
    # low-coverage bases). A demo written in lowercase would report 3,180
    # masked bases, which is not what this molecule is.
    out.append("ORIGIN")
    for i in range(0, N, 60):
        chunks = [seq[j:j + 10] for j in range(i, min(i + 60, N), 10)]
        out.append(f"{i + 1:>9} " + " ".join(chunks))
    out.append("//")

    text = "\n".join(out) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)

    n_sites = sum(len(find_sites(seq, p)) for _, p in PRIMERS)
    print(f"wrote {OUT}")
    print(f"  {N} bp circular, {len(FEATURES)} features, "
          f"{n_sites} primer binding site(s), {len(text):,} bytes")
    if n_sites == 0:
        print("  WARNING: no primer binds -- the primer panel will be empty")
    print("  verify with:  pl info prototype/demo-construct.gb")
    return 0


if __name__ == "__main__":
    sys.exit(main())
